name: Update CloudFront IPv4 list

on:
  workflow_dispatch: {} # Allow manual runs
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes

permissions:
  contents: write

jobs:
  update-cloudfront-list:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate cloudfront.list from MetaCubeX meta-rules-dat
        shell: bash
        run: |
          set -euo pipefail

          URL="https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/sing/geo/geoip/cloudfront.json"
          OUT_FILE="cloudfront.list"

          # Fetch and extract IPv4 CIDRs from rules.ip_cidr, exclude IPv6 (with ':'),
          # sort and deduplicate.
          curl -fsSL "$URL" \
            | jq -r '.rules.ip_cidr? // [] | .[]' \
            | grep -v ':' \
            | sort -u \
            > "$OUT_FILE"

          if [ ! -s "$OUT_FILE" ]; then
            echo "Generated $OUT_FILE is empty; aborting."
            exit 1
          fi

      - name: Commit and push changes (if any)
        shell: bash
        run: |
          set -euo pipefail

          # Ensure diff detects new file as well
          git add -N cloudfront.list

          if git diff --quiet -- cloudfront.list; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cloudfront.list
          git commit -m "chore: update cloudfront.list from MetaCubeX/meta-rules-dat"
          git push
